In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
class NGramLanguageModel: 
    def __init__(self, n):
        self.n = n
        self.vectorizer = CountVectorizer(analyzer='word', ngram_range=(n,n))
        
    def fit_transform(self, data): 
        return self.vectorizer.fit_transform(data)
    
    def transform(self, data): 
        return self.vectorizer.transform(data)

In [12]:
document = [
    'Try to Learning',
    'Natural Language Processing',
    'In Software Laboratory Class'
]

query = 'Try Query the Natural Language Processing Corpus'

In [28]:
n = 1    
nGramModel = NGramLanguageModel(n)

document_v = nGramModel.fit_transform(document)
query_v = nGramModel.transform([query])
pd.DataFrame(document_v.toarray(), columns=nGramModel.vectorizer.get_feature_names_out())

,class,in,laboratory,language,learning,natural,processing,software,to,try
0,0,0,0,0,1,0,0,0,1,1
1,0,0,0,1,0,1,1,0,0,0
2,1,1,1,0,0,0,0,1,0,0

In [26]:
def calculate_cosine_similarity(target, query): 
    return cosine_similarity(target, query)

In [29]:
similarity = calculate_cosine_similarity(document_v, query_v)

data = {
    'document': document, 
    'similarity': similarity.flatten()
}

pd.DataFrame(data) # n=1 (unigram)

                       document  similarity
0               Try to Learning    0.288675
1   Natural Language Processing    0.866025
2  In Software Laboratory Class    0.000000