# Language Model (N-Grams)

#### Vectorizing

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
class NGramLanguageModel: 
    def __init__(self, n):
        self.n = n
        self.vectorizer = CountVectorizer(analyzer='word', ngram_range=(n,n))
        
    def fit_transform(self, data): 
        return self.vectorizer.fit_transform(data)
    
    def transform(self, data): 
        return self.vectorizer.transform(data)

In [17]:
document = [
  'She sells sea shells by the sea shore',
  'The shells she sells are surely sea shells',
  'So if she sells sea shells on the sea shore'
]

query = 'Surely she sells sea shells'

In [ ]:
n = 1   # unigram = 1, bigram = 2, trigram = 3
nGramModel = NGramLanguageModel(n)

document_vector = nGramModel.fit_transform(document)
query_vector = nGramModel.transform([query])
pd.DataFrame(document_vector.toarray(), columns=nGramModel.vectorizer.get_feature_names_out())

   are  by  if  on  sea  sells  she  shells  shore  so  surely  the
0    0   1   0   0    2      1    1       1      1   0       0    1
1    1   0   0   0    1      1    1       2      0   0       1    1
2    0   0   1   1    2      1    1       1      1   1       0    1

In [ ]:
n = 2     # bigram
nGramModel = NGramLanguageModel(n)

document_vector = nGramModel.fit_transform(document)
query_vector = nGramModel.transform([query])
pd.DataFrame(document_vector.toarray(), columns=nGramModel.vectorizer.get_feature_names_out())

,are surely,by the,if she,on the,sea shells,sea shore,sells are,sells sea,she sells,shells by,shells on,shells she,so if,surely sea,the sea,the shells
0,0,1,0,0,1,1,0,1,1,1,0,0,0,0,1,0
1,1,0,0,0,1,0,1,0,1,0,0,1,0,1,0,1
2,0,0,1,1,1,1,0,1,1,0,1,0,1,0,1,0

In [25]:
n = 3     # trigram
nGramModel = NGramLanguageModel(n)

document_vector = nGramModel.fit_transform(document)
query_vector = nGramModel.transform([query])
pd.DataFrame(document_vector.toarray(), columns=nGramModel.vectorizer.get_feature_names_out())

,are surely sea,by the sea,if she sells,on the sea,sea shells by,sea shells on,sells are surely,sells sea shells,she sells are,she sells sea,shells by the,shells on the,shells she sells,so if she,surely sea shells,the sea shore,the shells she
0,0,1,0,0,1,0,0,1,0,1,1,0,0,0,0,1,0
1,1,0,0,0,0,0,1,0,1,0,0,0,1,0,1,0,1
2,0,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0

#### Cosine Similarity

In [19]:
def calculate_cosine_similarity(target, query): 
    return cosine_similarity(target, query)

In [ ]:
similarity = calculate_cosine_similarity(document_vector, query_vector)

data = {
    'document': document, 
    'similarity': similarity.flatten()
}

pd.DataFrame(data) # n=1 (unigram)

                                      document  similarity
0        She sells sea shells by the sea shore    0.707107
1   The shells she sells are surely sea shells    0.848528
2  So if she sells sea shells on the sea shore    0.645497